# Generated by Django 5.2.8 on 2025-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Идентификатор пользователя в Telegram для уведомлений.', max_length=64, null=True, unique=True),
        ),
    ]
