# Generated by Django 5.2.8 on 2025-11-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_telegram_id"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CREATOR", "Creator"), ("EXECUTOR", "Executor")],
                help_text="Роль пользователя в системе: CREATOR или EXECUTOR.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["invited_by"], name="idx_user_invited_by"),
        ),
    ]
