# Generated by Django 5.2.8 on 2025-11-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskactionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
