# Generated by Django 5.2.8 on 2025-11-20 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_reminder_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
