# Generated by Django 5.2.8 on 2025-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("general", "Общее вложение"),
                    ("result", "Результат выполнения"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
