# Generated by Django 5.2.8 on 2025-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_taskattachment_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="executor_comment",
            field=models.TextField(blank=True),
        ),
    ]
