# Generated by Django 5.2.8 on 2025-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="overdue_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
