# Generated by Django 5.2.8 on 2025-12-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_overdue_notified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="overdue_notified_at",
        ),
    ]
