# Generated by Django 5.2.8 on 2025-12-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_at",
        ),
    ]
