# 1. Сборка Vite
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Важно: VITE_API_BASE_URL="/api" чтобы фронт ходил на /api
ENV VITE_API_BASE_URL=/api
RUN npm run build

# 2. Nginx, который отдает фронт и проксирует /api -> backend:8000
FROM nginx:alpine

# Конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Статика фронта
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
